# Minimal docker-compose example for ChartSmith MCP
# Usage:
#   1) Create a .env next to this file (only needed if using AI features)
#   2) docker compose up -d

services:
  chartsmith-http:
    image: inwookie/chartsmith-mcp:latest
    command: python -m chart_genius_mcp --transport sse --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env

  chartsmith-stdio:
    image: inwookie/chartsmith-mcp:latest
    command: python -m chart_genius_mcp --transport stdio
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    restart: unless-stopped 